services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: publicinfo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whjqb1984
      POSTGRES_DB: publicinfo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  pgdata: